In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder #convert categorical variables into numerical variables
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics #evaluate the performance of machine learning models

In [3]:
#Loading data from csv file to a Pandas DataFrame
data = pd.read_csv("/Users/jianingjin/Downloads/venmo_cleaned.csv")

/var/folders/6j/4hpwlvm53rb7c9ytxmxhmnv00000gn/T/ipykernel_22962/42872284.py:2: DtypeWarning: Columns (9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/jianingjin/Downloads/venmo_cleaned.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7075081 entries, 0 to 7075080
Data columns (total 19 columns):
 #   Column                           Dtype
---  ------                           -----
 0   payment.id                       float64
 1   payment.date_completed           object
 2   payment.target.user.username     object
 3   payment.target.user.is_group     object
 4   payment.target.user.is_active    object
 5   payment.target.user.is_blocked   object
 6   payment.target.user.id           float64
 7   payment.target.user.date_joined  object
 8   payment.actor.username           object
 9   payment.actor.is_group           object
 10  payment.actor.is_active          object
 11  payment.actor.is_blocked         object
 12  payment.actor.id                 float64
 13  payment.actor.date_joined        object
 14  payment.note                     object
 15  payment.action                   object
 16  payment.date_created             object
 17  likes.count                      int64
 18  mentions.count                   int64
dtypes: float64(3), int64(2), object(14)
memory usage: 1.0+ GB

In [5]:
data.head()

,payment.id,payment.date_completed,payment.target.user.username,payment.target.user.is_group,payment.target.user.is_active,payment.target.user.is_blocked,payment.target.user.id,payment.target.user.date_joined,payment.actor.username,payment.actor.is_group,payment.actor.is_active,payment.actor.is_blocked,payment.actor.id,payment.actor.date_joined,payment.note,payment.action,payment.date_created,likes.count,mentions.count
0,2.540405e+18,2018-08-07T02:11:16,kimsionie,False,True,False,2.082497e+18,2016-11-13T07:09:48.000Z,Vitna-Kim,False,True,False,2.482900e+18,2018-05-19T18:00:04.000Z,fuk ya,pay,2018-08-07T02:11:16,0,0
1,2.540405e+18,2018-08-07T02:11:16,Kari-Joel-1,False,True,False,2.538731e+18,2018-08-04T18:45:48.000Z,Brian-Joel-1,False,True,False,2.363395e+18,2017-12-05T20:44:55.000Z,:venmo_dollar:,pay,2018-08-07T02:11:16,0,0
2,2.540405e+18,2018-08-07T02:11:15,JDR88,False,True,False,1.921316e+18,2016-04-04T21:51:04.000Z,Savannah-Landry-4,False,True,False,2.278060e+18,2017-08-10T02:59:07.000Z,ðŸŽ‰,pay,2018-08-07T02:11:15,0,0
3,2.540405e+18,2018-08-07T02:11:15,Dion-Nunez,False,True,False,2.019594e+18,2016-08-18T12:13:17.000Z,brttnygross,False,True,False,2.085027e+18,2016-11-16T18:56:55.000Z,Boyz,charge,2018-08-07T02:11:15,0,0
4,2.540405e+18,2018-08-07T02:11:15,AlecJameson,False,True,False,2.080895e+18,2016-11-11T02:07:34.000Z,treyhill094,False,True,False,2.029336e+18,2016-08-31T22:48:24.000Z,ðŸ¥©,pay,2018-08-07T02:11:15,0,0